### ISSUE TITLE
Cannot find module when running tests on Windows

### ISSUE THREAD

**Issue by villelahdenvuo** [vowsjs/vows#270]
I'm tried on 0.6.x and 0.7.0 It seems to be doubling the path for some reason. Here's what I get:

```
E:\Backup\Koodaus\node-irc-stream>vows -v -i
...
vows bin discovered ./test
vows runner loading [ 'E:\\Backup\\Koodaus\\node-irc-stream\\test\\JSHintTest', 'E:\\Backup\\Koodaus\\node-irc-stream\\t
est\\LoadMiddlewareTest', 'E:\\Backup\\Koodaus\\node-irc-stream\\test\\ParserTest' ]
vows runner running undefined
module.js:340
    throw err;
          ^
Error: Cannot find module 'E:\Backup\Koodaus\node-irc-stream\E:\Backup\Koodaus\node-irc-stream\test\JSHintTest'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at C:\Users\tuhoojabotti\AppData\Roaming\npm\node_modules\vows\bin\vows:567:19
    at Array.reduce (native)
    at importSuites (C:\Users\tuhoojabotti\AppData\Roaming\npm\node_modules\vows\bin\vows:560:18)
    at Object.<anonymous> (C:\Users\tuhoojabotti\AppData\Roaming\npm\node_modules\vows\bin\vows:290:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
...
```

**Comment by evanp** [comment]
vows 1.x doesn't automatically find the tests, so I'm going to close this for now.
