### ISSUE TITLE
Assert namespace shouldn't be modified and stack trace is not very readable

### ISSUE THREAD

**Issue by joekim** [vowsjs/vows#51]
Vows is a nice test library, but it should not modify the 'assert' namespace.  Further the stack trace that is printed when an assert fails is much LESS READABLE than the built in node one:

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
<error: TypeError: Cannot call method 'match' of undefined>
    at Object.<anonymous> (REMOVED)
    at run (/usr/local/lib/node/.npm/vows/0.5.3/package/lib/vows/suite.js:128:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node/.npm/vows/0.5.3/package/lib/vows/suite.js:200:40)
    at EventEmitter.emit (events.js:59:20)
    at Array.<anonymous> (/usr/local/lib/node/.npm/vows/0.5.3/package/lib/vows/suite.js:150:58)
    at EventEmitter._tickCallback (node.js:108:26)

Versus the one from node:

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
AssertionError: true == false
    at Object.<anonymous> (Removed)
    at Module._compile (module.js:287:26)
    at Object..js (module.js:293:10)
    at Module.load (module.js:219:31)
    at Function._load (module.js:186:10)
    at Array.<anonymous> (module.js:307:10)
    at EventEmitter._tickCallback (node.js:108:26)

---

Node's stack trace clearly says assertion failed, whereas the vows stack trace is complaining that you cannot call 'match' on undefined.

**Comment by evanp** [comment]
v1.x doesn't pollute the namespace, so I'm closing this.
